const PALETTE = {
  sky_top: "#78C9F1",
  sky_bottom: "#E9F6FF",
  grass: "#83DD62",
  grass_alt: "#A5EF75",
  soil: "#5E8B49",
  wood: "#B66C38",
  wood_dark: "#623A25",
  stone: "#B8B6A9",
  stone_dark: "#74766D",
  leaf: "#43A85A",
  leaf_light: "#72D36A",
  agent: "#4285F4",
  agent_dark: "#1D4E9D",
  agent_face: "#D9F4FF",
  goal: "#FFD45A",
  goal_glow: "#62F0D0",
  target: "#70D6E8",
  hazard: "#EB685C",
  shadow: "#172019",
};

export const PRIMITIVE_CATALOG = Object.freeze([
  primitive("ground", "Ground", "Layout", "Static", "Box", "Walkable grass and paving that supports the scene.", "Base floors and bounded walkable areas.", "terrain_grass", [6, 6, 0.2], [0, 0, -0.1], "static", "ground", { asset_id: "courtyard_ground", variant: "grass_pavers" }, "#83DD62"),
  primitive("wall", "Wall", "Layout", "Static", "Box", "A solid barrier that blocks movement.", "Room boundaries, dividers, and maze segments.", "plain_wall", [4.5, 0.35, 1.6], [0, 0, 0.8], "static", "wall", { asset_id: "courtyard_boundary", variant: "plain" }, "#B8B6A9"),
  primitive("platform", "Platform", "Layout", "Static", "Box", "A raised walkable surface.", "Decks, ledges, bridges, and elevation changes.", "wood_platform", [3.8, 3, 0.35], [0, 0, 0.55], "static", "platform", { asset_id: "courtyard_platform", variant: "wood" }, "#B66C38"),
  primitive("ramp", "Ramp", "Layout", "Static", "Ramp", "An inclined walkable surface.", "Connecting the ground to platforms without jumping.", "wood_ramp", [4, 2.4, 1.2], [0, 0, 0.45], "static", "ramp", { asset_id: "courtyard_ramp", variant: "wood" }, "#8B5634"),
  primitive("static_box", "Anchored Box", "Objects", "Static", "Box", "A crate-shaped obstacle that cannot move.", "Stable towers, steps, structures, and blockers.", "crate", [1.5, 1.5, 1.5], [0, 0, 0.75], "static", "static_box", { asset_id: "courtyard_static_prop", variant: "crate" }, "#B66C38"),
  primitive("pushable_box", "Pushable Box", "Objects", "Dynamic", "Box", "A movable supply crate affected by physics.", "Push puzzles, movable cover, and dynamic stacks.", "crate", [1.5, 1.5, 1.5], [0, 0, 0.75], "dynamic", "pushable_box", { asset_id: "courtyard_pushable_crate" }, "#D68143"),
  primitive("ball", "Ball", "Objects", "Dynamic", "Sphere", "A rolling round object affected by physics.", "Rolling obstacles and push interactions.", "boulder", [1.35, 1.35, 1.35], [0, 0, 0.68], "dynamic", "ball", null, "#8B9189"),
  primitive("cylinder", "Barrel", "Objects", "Dynamic", "Cylinder", "An upright movable cylinder that can tip and roll.", "Pushable clutter, lanes, and physics challenges.", "barrel", [1.2, 1.2, 1.7], [0, 0, 0.85], "dynamic", "cylinder", { asset_id: "courtyard_barrel" }, "#9A5B32"),
  primitive("agent", "Robot", "Gameplay", "Dynamic", "Cylinder", "The controllable blue service robot.", "Playable movement, jumping, and behavioral trials.", "agent_hero", [0.7, 0.7, 1.1], [0, 0, 0.55], "dynamic", "agent", { asset_id: "courtyard_robot" }, "#4285F4"),
  primitive("goal", "Goal Pad", "Gameplay", "Sensor", "Box", "A visible non-colliding success zone.", "Reach-goal scenes when a goal is explicitly requested.", "goal_pad", [1.7, 1.7, 1.2], [0, 0, 0.6], "sensor", "goal", { asset_id: "courtyard_goal_pad" }, "#62F0D0"),
  primitive("target_region", "Target Region", "Gameplay", "Sensor", "Box", "A neutral non-colliding region used by task tests.", "Object delivery, checkpoints, and non-goal trajectory objectives.", "target_region", [2, 2, 0.2], [0, 0, 0.1], "sensor", "target_region", { asset_id: "courtyard_target_region" }, "#70D6E8"),
  primitive("hazard", "Hazard", "Gameplay", "Sensor", "Box", "A clearly marked sensor zone that reports entry and exit events.", "Use it for task-specific risks, forbidden areas, checkpoints, or other rules defined by tests.", "courtyard_hazard", [2.4, 2, 0.15], [0, 0, 0.075], "sensor", "hazard", { asset_id: "courtyard_hazard", variant: "broken_paving" }, "#FFD43B"),
  primitive("floor_switch", "Floor Switch", "Mechanisms", "Sensor", "Box", "A floor trigger that latches a linked gate open.", "Pressure-switch and crate-triggered gate puzzles.", "floor_switch", [1.4, 1.4, 0.14], [0, 0, 0.07], "sensor", "floor_switch", { asset_id: "courtyard_floor_switch" }, "#FFD45A"),
  primitive("gate", "Sliding Gate", "Mechanisms", "Mechanism", "Box", "A solid gate that slides upward when activated.", "Blocking routes controlled by a floor switch.", "sliding_gate", [3.4, 0.35, 2.2], [0, 0, 1.1], "mechanism", "gate", { asset_id: "courtyard_gate" }, "#6B4A31"),
]);

export function primitivePreviewScene(item) {
  const support = item.id === "ground"
    ? []
    : [{
        id: "catalog_support",
        source_id: "catalog_support",
        physics_backed: false,
        semantic_type: "ground",
        visual_type: "terrain_grass",
        position: [0, 0, -0.1],
        size: [7, 7, 0.2],
        yaw: 0,
        body_type: "static",
        tags: ["walkable"],
        appearance: { asset_id: "courtyard_ground", variant: "grass_pavers" },
        metadata: {},
      }];
  return {
    schema_version: "1.0",
    source_env_id: `primitive_${item.id}`,
    theme: "robot_courtyard",
    world_size: [9, 9, 7],
    units: "meters",
    environment: {
      sky: { style: "courtyard_daylight", sun: true },
      set_dressing: { placement: "none", clear_play_area: true, grounding: "catalog" },
    },
    camera: {
      target: [0, 0, item.id === "ground" ? 0 : Math.max(0.45, item.position[2] * 0.8)],
      distance: item.cameraDistance || 6.2,
      min_distance: 3,
      max_distance: 12,
      azimuth: -38,
      elevation: item.id === "ground" ? 48 : 28,
    },
    palette: PALETTE,
    objects: [
      ...support,
      {
        id: `catalog_${item.id}`,
        source_id: item.id,
        physics_backed: true,
        semantic_type: item.semanticType,
        visual_type: item.visualType,
        position: item.position,
        size: item.size,
        yaw: item.id === "ramp" ? -0.18 : 0,
        body_type: item.bodyType,
        tags: [],
        appearance: item.appearance,
        metadata: item.id === "ramp" ? { height: item.size[2] } : {},
      },
    ],
    metadata: { source: "primitive_catalog", derived: true, decorations_are_visual_only: false },
  };
}

function primitive(
  id,
  label,
  category,
  physicsLabel,
  shapeLabel,
  description,
  use,
  visualType,
  size,
  position,
  bodyType,
  semanticType,
  appearance,
  color,
) {
  return Object.freeze({
    id,
    label,
    category,
    physicsLabel,
    shapeLabel,
    description,
    use,
    visualType,
    size,
    position,
    bodyType,
    semanticType,
    appearance,
    color,
  });
}
